# Generated by Django 5.2.4 on 2026-09-02 08:31

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('rejection_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='catalogitem',
            name='accounts_ca_color_f_cdd78c_idx',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='color_palette_tags',
            new_name='compatible_color_palette_tags',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounts.uploadbatch'),
        ),
    ]
