# Generated by Django 5.2.4 on 2026-09-05 05:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='front_image',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.GridFSStorage(), upload_to='catalog/front/'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.GridFSStorage(), upload_to='catalog/rear/'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='side_image',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.GridFSStorage(), upload_to='catalog/side/'),
        ),
    ]
