# Generated by Django 6.0.8 on 2026-09-23 12:59

import accounts.storage
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_moved_models_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('rejection_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_uploadbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('color_description', models.TextField()),
                ('color_family', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('occasion_tags', models.JSONField(blank=True, default=list)),
                ('compatible_color_palette_tags', models.JSONField(blank=True, default=list)),
                ('store_name', models.CharField(max_length=255)),
                ('front_image', models.ImageField(blank=True, null=True, storage=accounts.storage.GridFSStorage(), upload_to='catalog/front/')),
                ('side_image', models.ImageField(blank=True, null=True, storage=accounts.storage.GridFSStorage(), upload_to='catalog/side/')),
                ('rear_image', models.ImageField(blank=True, null=True, storage=accounts.storage.GridFSStorage(), upload_to='catalog/rear/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.uploadbatch')),
            ],
            options={
                'db_table': 'accounts_catalogitem',
                'indexes': [models.Index(fields=['category', 'status'], name='accounts_ca_categor_ad4d38_idx'), models.Index(fields=['seller', 'status'], name='accounts_ca_seller__0dab08_idx')],
            },
        ),
            ],
        ),
    ]
