# Generated by Django 6.0.8 on 2026-09-23 12:59

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_moved_models_state_only'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='AvatarPreset',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height', models.IntegerField(help_text='Height in cm')),
                ('weight', models.IntegerField(help_text='Weight in kg')),
                ('skin_tone', models.CharField(default='medium', max_length=32)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('shoulder', models.CharField(choices=[('narrow', 'Narrow'), ('average', 'Average'), ('broad', 'Broad')], default='average', max_length=10)),
                ('waist', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('curvy', 'Curvy')], default='average', max_length=10)),
                ('hip', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('wide', 'Wide')], default='average', max_length=10)),
                ('cup_size', models.CharField(blank=True, choices=[('', 'Not applicable'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2)),
                ('thigh', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('thick', 'Thick')], default='average', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_avatarpreset',
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='outfits', to='catalog.catalogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_outfit',
            },
        ),
            ],
        ),
    ]
