# Generated by Django 6.0.8 on 2026-09-25 03:17

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('item', 'Catalog Item'), ('fit', 'Fit Visualization')], max_length=10)),
                ('target_id', models.CharField(max_length=50)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_rating',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='accounts_ra_target__7a80f1_idx')],
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
    ]
